config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  resources :users
 
  resources :sessions, only: [:new, :create, :destroy]

  resources :photos

  resources :upcomings

  resources :events
  
  get '/login', to: 'sessions#new'

  resources :posts do 
    resources :comments, shallow:true
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/upcoming.rb
class Upcoming < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many  :comments, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  helper_method :current_user, :display_month_birthday
  
  def display_month_birthday birthday
    if !birthday
      return false
    end
    birthday_arr = birthday.to_s.split('-')
    month = birthday_arr[1] 
    day = birthday_arr[2]
    if Date.current.to_s.split("-")[1] == month
      return month + '/' + day
    end
    return false
  end

  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

helper_method :is_public
 
  def index
  end
  
  def new
    @event = Event.new
    @events = Event.where('date >= ?', DateTime.now).order(:date)
  end
  
  def create
    @event = Event.new(event_params)
      if @event.save
      redirect_to users_path
    else
      render :new
    end
  end
 
  def show   
      @event = Event.find(params[:id])
  end

  def destroy
      @event = Event.find(params[:id])
      @event.destroy
      redirect_to users_path
  end 

  def edit
      @event = Event.find(params[:id])
      @events = Event.where('date >= ?', DateTime.now)
  end

  def update
      @events = Event.where('date >= ?', DateTime.now)
      @event = Event.find(params[:id])
        if @event.update_attributes(params.require(:event).permit(:title, :date))
          redirect_to users_path
        else
          render :edit
        end
  end
  
  def is_public
    @event = Event.where('date >= ?', 'public == True')
  end

  
private

  def event_params
    params.require(:event).permit(:title, :date, :public)
  end

end

    

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @events = Event.where(public: true)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
  end
  
  def destroy
      @photo = Photo.find(params[:id])
      @photo.destroy
      redirect_to photos_path
  end 


  def create
    @new_photo = params.require(:photo).permit(:image, :content)
    @photo = Photo.new(@new_photo)
    @photo.user_id = current_user.id

    if @photo.save
      redirect_to :photos
    else
      redirect_to :posts
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
      @posts = Post.order(created_at: :desc)
      @post = Post.new
      @events = Event.where('date >= ?', DateTime.now).order(:date) 
      @photo = Photo.new    
    end
   
    def create
      @post = Post.new(params.require(:post).permit(:content))
      @post.user = current_user
      @post.save
      redirect_to posts_path
    end
 
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
    end 
 
    def edit
      @post = Post.find(params[:id])
      @events = Event.where('date >= ?', DateTime.now)
    end

    def update
      @post = Post.find(params[:id])
      if @post.update_attributes(params.require(:post).permit(:content))
        redirect_to posts_path
      else
        render :edit
      end
    end

    private
      def post_params
        params.require(:post).permit(:content)
      end


  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    puts "hi"
  end

  def create  
    user = User.find_by(email: params[:email])  
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  helper_method :display_month_birthday

  def index
    @users_alphabetical = User.all.order(:name)
    @users_birthday = User.all.order(:birthday)
    @events = Event.where('date >= ?', DateTime.now).order(:date)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up!"
      redirect_to users_path
    else
      render :new
    end   
  end

  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
  end 
  
  def edit
      @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params.require(:user).permit(:name, :email, :password_digest, :birthday))
      redirect_to users_path
    else
      render :edit
    end
  end

  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :birthday,:image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h2>Members Area</h2>

<div class="row">
  <div class="col-md-4">
    <h3>Edit Event</h3>

      <%= form_for @event do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :date %>
          <%= f.date_field :date, class: "form-control" %>     
        </div>
          <%= f.submit "Edit event", class: "btn btn-success"%>
        <% end %>
  </div>

  <div class="col-md-4">
  </div>

  <div class="col-md-4">
      <h3>Upcoming Events</h3>
        <% if @events.count == 0 %>
          <h5>No Events Yet!</h5>
        <% else %>
          <% @events.each do |event| %>
            <div>
              <strong><%= event.title %></strong>
            </div>
            <div>
                <%= event.date %>
            </div>
            <div>
              <%= link_to "edit event", edit_event_path(event), class: "btn btn-xs btn-warning text-right" %>         
              <%= link_to "delete event", event_path(event), class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this event?"} %>
            </div>
          <% end %>
        <% end %>
  </div>   

</div>

app/views/events/index.html.erb
<h2>Members Area</h2>

  <div class="row">
    <div class="col-md-4">
      <h3>Members</h3>
      <% @users.each do |user|%>
        <div>
          <strong><%= user.name %></strong>  
        </div>
        <div>
            <%= link_to "edit member", edit_user_path(user), class: "btn btn-xs btn-warning text-right" if user == current_user %>             
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <h3>This Month's Birthdays</h3>
      <% @users.each do |user|%>
        <% if display_month_birthday(user.birthday) %>
          <div>
            <strong><%= user.name %></strong> - 
          </div>
          <div>
            <%= display_month_birthday(user.birthday) %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="col-md-4">
      <h3>Upcoming Events</h3>
      <% if @events.count == 0 %>
        <h5>No Events Yet!</h5>
      <% else %>
      <% @events.each do |event| %>
        <div>
          <strong><%= event.title %></strong>
        </div>
        <div>
            <%= event.date %>
        </div>
        
        <div>
            <%= link_to "edit event", edit_event_path(event), class: "btn btn-xs btn-warning text-right" %>         
            <%= link_to "delete event", event_path(event), class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this event?"} %>
          </div>
        <% end %>
      <% end %>
    </div>  
  </div>
</div>

app/views/events/new.html.erb
<h2>Members Area</h2>

<div class="row">
  <div class="col-md-4">
    <h3>Create new event</h3>
    <%= form_for @event do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :date %>
        <%= f.date_field :date, class: "form-control" %>     
      </div>
      <div class="form-group">
        <%= f.label :public, "Is this a public event(concert, workshop, etc) " %>
        <%= f.check_box :public %>
      </div>
      <div>
        <%= f.submit "Create Event", class: "btn btn-success"%>
      </div>
    <% end %>   
  </div>

  <div class="col-md-4">
  </div>
  
  <div class="col-md-4">
    <h3>Upcoming Events</h3>
    <% if @events.count == 0 %>
      <h5>No Events Yet!</h5>
    <% else %>
      <% @events.each do |event| %>
        <div>
          <strong><%= event.title %></strong>
        </div>
        <div>
            <%= event.date.strftime("%b %d, %Y") %>
        </div>
        
        <div>
            <%= link_to "edit event", edit_event_path(event), class: "btn btn-xs btn-warning text-right" %>         
            <%= link_to "delete event", event_path(event), class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this event?" } %>
          </div>
      <% end %>
    <% end %>
  </div>
</div>

   
  
  



      
   
 

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<div class="wrapper">
  <div class="row">
    <div class="col-md-8">
      <h2>About Us</h2>
      <p class="about">
      <span class="lead">Burat Wangi</span> is Southern California’s best known gamelan orchestra specializing in the music and dance of Bali. Founded in 1972 by world-renowned musicians and dancers I Nyoman Wenten, Nanik Wenten, and K.P.H. Notoprojo, the group performs a diverse repertoire of traditional and new music by Bali’s most famous composers and choreographers.  
      <br>
      <br>
      In recent years, the group has performed at: Disney Hall (World Music Subscription Series), Japan America Theatre, California Institute of the Arts Musical Exploration Series, REDCAT Theatre, Grand Performances at California Plaza, Mingei Museum (San Diego),The Getty Center, Los Angeles Lotus Festival, the home of the Indonesian Consul in Los Angeles, and at the wedding of the Prince of Malaysia.  
      <br>
      <br>
      The 30-member group enjoys a reputation for its professionalism, musicianship, and mastery of traditional arts.  Burat Wangi is frequently joined by guest artists of the highest rank, including I Dewa Putu Berata and I Nyoman Cerita, who have also contributed significant works to the group’s repertoire.  Many group members have pursued independent music study in Bali, some of them funded by the Fulbright Foundation.  
      </p>
    </div>
   
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamelanBuratWangi</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Posts', posts_path %></a></li>
            <li><%= link_to 'Events', new_event_path %></a></li>
            <li><%= link_to 'Members', users_path %></a></li>
            <li><%= link_to 'Photos', photos_path %></a></li>
          </ul>
          <% end %>
      
          <ul class="nav navbar-nav ">
            <% if current_user %>      
              <li><p class="navbar-text">Welcome, <%= current_user.name %></p></li>
              <li><%= link_to 'Log Out', session_path('dummy'), method: :delete %></li>
            <% else %>
              <li><%= link_to 'Log In', login_path %></li>
              <li><%= link_to 'Sign Up', new_user_path %></li>
            <% end %>   
          </ul>

    </div>
  </div>
  
</nav>
    <div class="jumbotron text-center heading"><h1>Gamelan Burat Wangi</h1></div>
    <%= yield %>    
  </body>
</html>

app/views/photos/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-4">
            <% @photos.each_with_index do |photo, idx| %>
                <% if idx % 3 == 0 %>
                    <div>
                        <%= image_tag photo.image.url, class: "medium" %>
                        <br>
                        <%= photo.content %>
                        <%= link_to "delete photo", photo_path(photo), class: "btn btn-xs btn-danger", method: :delete, data: { confirm:
                        "Are you sure you want to delete this photo?"} if photo.user == current_user %>  
                    </div>
                <% end %>    
            <% end %>
        </div>
        <div class="col-xs-4">
            <% @photos.each_with_index do |photo, idx| %>
                <% if idx % 3 == 1 %>
                    <div>
                        <%= image_tag photo.image.url, class: "medium" %>
                        <br>
                        <%= photo.content %>
                        <%= link_to "delete photo", photo_path(photo), class: "btn btn-xs btn-danger", method: :delete, data: { confirm:
                        "Are you sure you want to delete this photo?"} if photo.user == current_user %>  
                    </div>
                <% end %>    
            <% end %>
        </div>
        <div class="col-xs-4">
            <% @photos.each_with_index do |photo, idx| %>
                <% if idx % 3 == 2 %>
                    <div>
                        <%= image_tag photo.image.url, class: "medium" %>
                        <br>
                        <%= photo.content %>
                        <%= link_to "delete photo", photo_path(photo), class: "btn btn-xs btn-danger", method: :delete, data: { confirm:
                        "Are you sure you want to delete this photo?"} if photo.user == current_user %>  
                    </div>
                <% end %>    
            <% end %>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<h2>Members Area</h2>

<div class="row">
  <div class="col-md-4">
    <h3>Edit Post</h3>
    <%= form_for @post do |f| %>   
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_field :content, class: "form-control" %>
      </div>
      <%= f.submit "Edit post", class: "btn btn-success"%>
    <% end %>
  </div>
  
  <div class="col-md-4">
  </div>

  <div class="col-md-4">
      <h3>Upcoming Events</h3>
      <% if @events.count == 0 %>
      <h5>No Events Yet!</h5>
      <% else %>
        <% @events.each do |event| %>
          <div>
            <strong><%= event.title %></strong>
          </div>
          <div>
              <%= event.date %>
          </div>         
        <% end %>
      <% end %>
  </div>  
</div>

app/views/posts/index.html.erb
<h2>Members Area</h2>

<div class="row">
  <div class="col-md-4">
    <h3>Create new post</h3>
    <%= form_for @post do |f| %>
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_field :content, class: "form-control" %>
      </div>
    <div>
        <%= f.submit "Create Post", class: "btn btn-success"%>
      </div>
    <% end %>

    <h3>Add photos</h3>
      <div class="form-group">
        <%= form_for [@photo] do |f| %>
          <div class="form-group">
            <%= f.file_field :image, :required => true, class: "form-control" %>
            <%= f.text_field :content, placeholder: "title", class: "form-control" %>
          </div>
      <div class="form-group">
        <%= f.submit 'Add Photo', class: 'btn btn-primary' %>
      <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
  <br>
  <br>
    <% if @posts.count == 0 %>
      <h5>No Posts Yet!</h5>
    <% else %>
      <% @posts.each do |post| %>
        <div class="panel panel-default">
          <div class="panel-heading">
           <%= post.user.name %> 
            <%= post.created_at.in_time_zone("Pacific Time (US & Canada)").strftime("%b %e, %l:%M %p") %>
          </div>
          <div class="panel-body">
            <%= post.content %>
          </div>
          <div class="panel-footer">
            <%= link_to "edit post", edit_post_path(post), class: "btn   btn-xs btn-warning text-right" if post.user == current_user %>         
            <%= link_to "delete post", post_path(post), class: "btn btn-xs btn-danger", method: :delete, data: { confirm:
            "Are you sure you want to delete this post?"} if post.user == current_user %>       
          </div>         
        </div>
      <% end %>    
    <% end %> 
  </div>

  <div class="col-md-4">
    <h3>Upcoming Events</h3>
    <% if @events.count == 0 %>
      <h5>No Events Yet!</h5>
    <% else %>
      <% @events.each do |event| %>
        <div>
          <strong><%= event.title %></strong>
        </div>
        <div>
            <%= event.date.strftime("%b %d, %Y") %>
        </div>  
      <% end %>
    <% end %>
    </div>  
    
</div>


      
   
 

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-4">

    <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
            <div class="error_messages">
                <h2>Form is invalid</h2>
                <ul>
                    <% for message in @user.errors.full_messages %>
                        <li>
                            <%= message %>
                        </li>
                        <% end %>
                </ul>
            </div>
        <% end %>
    <div class="wrapper">
        <div class = "new_user">
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :birthday %>
                <%= f.date_field :birthday, class: "form-control" %>
                <span>year will not be displayed</span>
            </div>

            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
        </div>

        <div class="form-group text-center">
                <%= f.submit 'Add Photo', class: 'btn btn-primary' %>
        </div>
        
        <div class="text-center">
        <button type="submit" class="btn btn-success" >Edit User</button>
        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h2>Members Area</h2>

  <div class="row">
    <div class="col-md-4">
      <h3>Members</h3>
      <% @users_alphabetical.each do |user|%>
      <div>
       
      <%= link_to "delete", user_path(user), method: :delete if current_user && current_user.admin  %>
      <strong><%= user.name %></strong>&nbsp; &nbsp;<%= link_to "edit member", edit_user_path(user), class: "btn btn-xs btn-warning text-right" if user == current_user %>
      
      </div>  
      <% end %>
    </div>

    <div class="col-md-4">
      <h3>This Month's Birthdays</h3>
      <% @users_birthday.each do |user|%>
        <% if display_month_birthday(user.birthday) %>
          <div>
            <strong><%= user.name %></strong> 
          </div>
          <div>
            <%= user.birthday.strftime("%b %d") %>
          </div>
         
        <% end %>
      <% end %>
    </div>

    <div class="col-md-4">
      <h3>Upcoming Events</h3>
      <% if @events.count == 0 %>
      <h5>No Events Yet!</h5>
      <% else %>
      <% @events.each do |event| %>
        <div>
          <strong><%= event.title %></strong>
        </div>
        <div>
            <%= event.date.strftime("%b %d, %Y") %>
        </div>
        
        <% end %>
      <% end %>
    </div>  
    
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-4">

    <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
            <div class="error_messages">
                <h2>Form is invalid</h2>
                <ul>
                    <% for message in @user.errors.full_messages %>
                        <li>
                            <%= message %>
                        </li>
                        <% end %>
                </ul>
            </div>
        <% end %>
    <div class="wrapper">
        <div class = "new_user">
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :birthday %>
                <%= f.date_field :birthday, class: "form-control" %>
                <span>year will not be displayed</span>
            </div>

            <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.file_field :image, :required => true, class: "form-control" %>
            </div>

            <div class="form-group text-center">
                <%= f.submit 'Add Photo', class: 'btn btn-primary' %>
            </div>
            
        </div>
        
        <div class="text-center">
        <button type="submit" class="btn btn-success" >Create User</button>
        <% end %>
        </div>

        
        
    </div>
  </div>
</div>